warehouse = WeightedDiGraph()
warehouse.add_node('despatch')
warehouse.add_node('A')
warehouse.add_node('D')
warehouse.add_node('P')
warehouse.add_node('S')
warehouse.add_node('U')
warehouse.add_node('Y')
warehouse.add_node('Z')

warehouse.add_edge('despatch','U',30)
warehouse.add_edge('U','despatch',30)
warehouse.add_edge('despatch','A',10)
warehouse.add_edge('A','despatch',10)
warehouse.add_edge('despatch','D',5)
warehouse.add_edge('D','despatch',5)
warehouse.add_edge('despatch','Z',16)
warehouse.add_edge('Z','despatch',16)
warehouse.add_edge('A','U',15)
warehouse.add_edge('U','A',15)
warehouse.add_edge('A','P',10)
warehouse.add_edge('P','A',10)
warehouse.add_edge('P','S',12)
warehouse.add_edge('S','P',12)
warehouse.add_edge('D','Z',8)
warehouse.add_edge('Z','D',8)
warehouse.add_edge('P','D',15)
warehouse.add_edge('D','P',15)
warehouse.add_edge('P','Y',8)
warehouse.add_edge('Y','P',8)
warehouse.add_edge('Y','S',12)
warehouse.add_edge('S','Y',12)
warehouse.add_edge('Y','Z',15)
warehouse.add_edge('Z','Y',15)

warehouse.draw()
